// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package room

import (
	fmt "fmt"
	math "math"

	"context"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//  Room 会生成 Room 命名的结构体
type Room struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//  RoomInfo 会生成 RoomInfo 命名的结构体
type RoomInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//  RoomReq 会生成 RoomReq 命名的结构体
type RoomReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomReq) Reset()         { *m = RoomReq{} }
func (m *RoomReq) String() string { return proto.CompactTextString(m) }
func (*RoomReq) ProtoMessage()    {}
func (*RoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *RoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReq.Unmarshal(m, b)
}
func (m *RoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReq.Marshal(b, m, deterministic)
}
func (m *RoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReq.Merge(m, src)
}
func (m *RoomReq) XXX_Size() int {
	return xxx_messageInfo_RoomReq.Size(m)
}
func (m *RoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReq proto.InternalMessageInfo

func (m *RoomReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//  RoomRsp 会生成 RoomRsp 命名的结构体
type RoomRsp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRsp) Reset()         { *m = RoomRsp{} }
func (m *RoomRsp) String() string { return proto.CompactTextString(m) }
func (*RoomRsp) ProtoMessage()    {}
func (*RoomRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *RoomRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRsp.Unmarshal(m, b)
}
func (m *RoomRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRsp.Marshal(b, m, deterministic)
}
func (m *RoomRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRsp.Merge(m, src)
}
func (m *RoomRsp) XXX_Size() int {
	return xxx_messageInfo_RoomRsp.Size(m)
}
func (m *RoomRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRsp proto.InternalMessageInfo

func (m *RoomRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Room)(nil), "room.Room")
	proto.RegisterType((*RoomInfo)(nil), "room.RoomInfo")
	proto.RegisterType((*RoomReq)(nil), "room.RoomReq")
	proto.RegisterType((*RoomRsp)(nil), "room.RoomRsp")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

// client
type StreamClient interface {
	SayHello(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*RoomRsp, error)
}

type streamClient struct {
	cc *grpc.ClientConn
}

func NewStreamClient(cc *grpc.ClientConn) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) SayHello(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*RoomRsp, error) {
	out := new(RoomRsp)
	err := c.cc.Invoke(ctx, "/streamSERVER/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// server
type StreamServer interface {
	SayHello(ctx context.Context, in *RoomReq) (*RoomRsp, error)
}

func RegisterStreamServer(s *grpc.Server, srv StreamServer) {
	s.RegisterService(&_Stream_serviceDesc, srv)
}

var _Stream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streamSERVER",
	HandlerType: (*StreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _StreamService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room.proto",
}

func _StreamService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamSERVER/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServer).SayHello(ctx, req.(*RoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xb4, 0xb8, 0x58, 0x82, 0xf2,
	0xf3, 0x73, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98,
	0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x25, 0x39, 0x2e, 0x0e, 0x90, 0x5a, 0xcf, 0xbc, 0xb4, 0x7c, 0xb8, 0x3c, 0x23,
	0x92, 0xbc, 0x2c, 0x17, 0x3b, 0x48, 0x3e, 0x28, 0xb5, 0x10, 0xaf, 0x74, 0x71, 0x01, 0x36, 0x69,
	0x23, 0x1b, 0x2e, 0xae, 0x80, 0xd2, 0xe2, 0x8c, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0x5c, 0x21, 0x3d,
	0x14, 0x1e, 0x9f, 0x1e, 0xd8, 0xe1, 0x30, 0xdb, 0xa5, 0xd0, 0xf8, 0x4a, 0x0c, 0x49, 0x6c, 0x60,
	0x4f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x98, 0x12, 0x55, 0xe2, 0x00, 0x00, 0x00,
}
