// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream_info.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamPoint struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamPoint) Reset()         { *m = StreamPoint{} }
func (m *StreamPoint) String() string { return proto.CompactTextString(m) }
func (*StreamPoint) ProtoMessage()    {}
func (*StreamPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b230a2dd9607b0e, []int{0}
}

func (m *StreamPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamPoint.Unmarshal(m, b)
}
func (m *StreamPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamPoint.Marshal(b, m, deterministic)
}
func (m *StreamPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPoint.Merge(m, src)
}
func (m *StreamPoint) XXX_Size() int {
	return xxx_messageInfo_StreamPoint.Size(m)
}
func (m *StreamPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPoint.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPoint proto.InternalMessageInfo

func (m *StreamPoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamPoint) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type StreamRequest struct {
	Pt                   *StreamPoint `protobuf:"bytes,1,opt,name=pt,proto3" json:"pt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b230a2dd9607b0e, []int{1}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetPt() *StreamPoint {
	if m != nil {
		return m.Pt
	}
	return nil
}

type StreamResponse struct {
	Pt                   *StreamPoint `protobuf:"bytes,1,opt,name=pt,proto3" json:"pt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b230a2dd9607b0e, []int{2}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetPt() *StreamPoint {
	if m != nil {
		return m.Pt
	}
	return nil
}

type StreamService_ListServer interface {
    Send(*StreamResponse) error
    grpc.ServerStream
}

func (x *streamServiceListServer) Send(m *StreamResponse) error {
    return x.ServerStream.SendMsg(m)
}
func init() {
	proto.RegisterType((*StreamPoint)(nil), "proto.StreamPoint")
	proto.RegisterType((*StreamRequest)(nil), "proto.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "proto.StreamResponse")
}

func init() { proto.RegisterFile("stream_info.proto", fileDescriptor_6b230a2dd9607b0e) }

var fileDescriptor_6b230a2dd9607b0e = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xce, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x70, 0x53, 0x36, 0x0b, 0xce, 0xa2, 0xe0, 0xb0, 0xc2, 0xe2, 0x69, 0xc9, 0xa9, 0xa7,
	0xa5, 0xb4, 0x42, 0xd1, 0x67, 0xf0, 0x20, 0xe9, 0x03, 0x48, 0xad, 0x23, 0x04, 0x6c, 0x12, 0x93,
	0x69, 0x5f, 0xcf, 0x57, 0x13, 0x12, 0x0b, 0xea, 0x69, 0x7b, 0xca, 0x9f, 0x8f, 0xdf, 0x7c, 0x03,
	0x37, 0x91, 0x03, 0xf5, 0xe3, 0x8b, 0xb1, 0xef, 0xee, 0xe4, 0x83, 0x63, 0x87, 0x32, 0x1d, 0xaa,
	0x85, 0x5d, 0x97, 0xb2, 0x67, 0x67, 0x2c, 0x23, 0xc2, 0xc6, 0xf6, 0x23, 0x1d, 0xc4, 0x51, 0x94,
	0x97, 0x3a, 0xdd, 0x71, 0x0f, 0x72, 0xee, 0x3f, 0x26, 0x3a, 0x14, 0x47, 0x51, 0x4a, 0x9d, 0x1f,
	0xaa, 0x81, 0xab, 0x0c, 0x35, 0x7d, 0x4e, 0x14, 0x19, 0x15, 0x14, 0x9e, 0x13, 0xdc, 0xd5, 0x98,
	0x4b, 0x4e, 0xbf, 0x46, 0xeb, 0xc2, 0xb3, 0xba, 0x87, 0xeb, 0x05, 0x45, 0xef, 0x6c, 0xa4, 0x73,
	0x54, 0xfd, 0x25, 0x96, 0xae, 0x8e, 0xc2, 0x6c, 0x06, 0xc2, 0x16, 0x36, 0x4f, 0x26, 0x32, 0xee,
	0xff, 0x88, 0x9f, 0x4d, 0xee, 0x6e, 0xff, 0xfd, 0xe6, 0x2a, 0x75, 0x51, 0x09, 0x7c, 0x80, 0xad,
	0xa6, 0xc1, 0x85, 0xb7, 0x95, 0xb4, 0x14, 0xf8, 0x08, 0x52, 0xbb, 0x89, 0x69, 0xb5, 0xac, 0xc4,
	0xeb, 0x36, 0x65, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x73, 0x1d, 0xc5, 0x88, 0x01,
	0x00, 0x00,
}
